name: ELSiP
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - debugpy=1.8.15=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.0.0=py310h71f11fc_0
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - aslide==1.2.0
      - backports-datetime-fromisoformat==2.0.3
      - bcrypt==4.3.0
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - clamlite==0.0.4
      - click==8.2.1
      - cmake==4.0.3
      - conch==0.1.0
      - contourpy==1.3.2
      - cryptography==45.0.5
      - cycler==0.12.1
      - dill==0.4.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - einops-exts==0.0.4
      - environs==11.0.0
      - et-xmlfile==2.0.0
      - fairscale==0.4.13
      - filelock==3.18.0
      - flash-attn==2.5.8
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - future==1.0.0
      - geopandas==1.1.1
      - gigapath==0.1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.4
      - idna==3.10
      - ipywidgets==8.1.7
      - jinja2==3.1.6
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lit==18.1.8
      - llvmlite==0.44.0
      - madeleine==0.0.1
      - markupsafe==3.0.2
      - marshmallow==4.0.0
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - ninja==1.13.0
      - nmslib==2.1.1
      - numba==0.61.2
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - openai-clip==1.0.1
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - openslide-bin==4.0.0.8
      - openslide-python==1.2.0
      - pandas==2.2.3
      - paramiko==3.5.1
      - pathos==0.3.3
      - pathtools==0.1.2
      - pillow==11.2.1
      - pip==25.2
      - pox==0.3.6
      - ppft==1.7.7
      - protobuf==4.25.8
      - pybind11==2.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pynacl==1.5.0
      - pynndescent==0.5.13
      - pyogrio==0.11.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - scp==0.15.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.5.0
      - sentry-sdk==2.33.2
      - setproctitle==1.3.6
      - setuptools==65.6.3
      - shapely==2.1.1
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - timm==0.9.16
      - timm-ctp==0.5.4
      - tokenizers==0.19.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.66.6
      - transformers==4.42.4
      - trident==0.2.0
      - triton==3.4.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wandb==0.21.1
      - widgetsnbextension==4.0.14
prefix: /home/fuyu/miniconda3/envs/clam
